---
language: ruby
sudo: false
cache: bundler
bundler_args: --without yard benchmarks
install: 'travis_retry bin/setup'
script: 'bundle exec appraisal rake ci'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
matrix:
  include:
    - rvm: jruby-19mode
    - rvm: jruby-20mode
    - rvm: jruby-21mode
    - rvm: jruby-head
    - rvm: rbx-2
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.1.0
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/rails32.gemfile
    - rvm: 2.3.0
      gemfile: gemfiles/rails32.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-20mode
    - rvm: jruby-21mode
  fast_finish: true
branches:
  only: master
notifications:
  email: false
