language: ruby
sudo: false
bundler_args: --without yard benchmarks
install: 'travis_retry bin/setup'
script: 'bundle exec appraisal rake ci'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
matrix:
  include:
    - rvm: jruby-19mode
    - rvm: jruby-20mode
    - rvm: jruby-21mode
    - rvm: jruby-head
    - rvm: rbx-2
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-20mode
    - rvm: jruby-21mode
  fast_finish: true
branches:
  only: master
