---
language: ruby
sudo: false
cache: bundler
install:
  - bundle install
  - bundle exec bin/appraisal install
script:
  - bundle exec appraisal rake ci
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - 2.4.1
matrix:
  include:
    - rvm: jruby-9.1.1.0
    - rvm: jruby-head
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/rails5.0.gemfile
    - rvm: 2.2.5
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails3.2.gemfile
    - rvm: 2.4.1
      gemfile:
        - gemfiles/rails3.2.gemfile
        - gemfiles/rails4.0.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.1.0
    - rvm: jruby-head
  fast_finish: true
branches:
  only: master
notifications:
  email: false
